" 文字コードをUTF-8
set fenc=utf-8
" 文字エンコーディングをUTF-8
set encoding=utf-8
" 行番号表示
set number
" タイトル表示
set title
" UNDOファイルを作らない
set noundofile
" バックアップファイルを作らない
set nobackup
" スワップファイルを作らない
set noswapfile
" 外部変更を反映する
set autoread
" 対応する括弧を強調表示
set showmatch
" タブ数を4
set tabstop=4
" スマートインデント
set smartindent
" 小文字検索ではignorecase, 大文字を含む場合は完全一致
set smartcase
" yankをクリップボードにも反映
set clipboard+=unnamed
" 折り返し表示無効
set nowrap
" ファイル読み込み時のencoding
set fileencodings=ucs-bom,iso-2022-jp-3,iso-2022-jp,eucjp-ms,euc-jisx0213,euc-jp,sjis,cp932,utf-8
" 水平スクロールバーを表示
set guioptions+=b
" 起動時のメッセージを消す
set shortmess+=I
" シンタックスハイライト
syntax on
" CUIテーマ
colorscheme delek
